# Generated by Django 5.2.8 on 2026-06-06 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_dep', models.AutoField(primary_key=True, serialize=False)),
                ('name_dep', models.CharField(default='Служба інформаційних технологій', max_length=150)),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='DictPos',
            fields=[
                ('id_pos', models.AutoField(primary_key=True, serialize=False)),
                ('name_pos', models.CharField(db_column='Name_pos', max_length=150)),
            ],
            options={
                'db_table': 'Dict_pos',
            },
        ),
        migrations.CreateModel(
            name='DictServ',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('domen', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Dict_serv',
            },
        ),
        migrations.CreateModel(
            name='Dictapplic',
            fields=[
                ('id_applic', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=150)),
                ('app_type', models.CharField(max_length=100)),
                ('app_disc', models.TextField(blank=True, null=True)),
                ('data_begin', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('id_server', models.ForeignKey(db_column='id_server', on_delete=django.db.models.deletion.CASCADE, to='main.dictserv')),
            ],
            options={
                'db_table': 'Dictapplic',
            },
        ),
        migrations.CreateModel(
            name='GroupD',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('opption', models.IntegerField()),
                ('id_app', models.ForeignKey(db_column='id_app', on_delete=django.db.models.deletion.CASCADE, to='main.dictapplic')),
            ],
            options={
                'db_table': 'Group_d',
            },
        ),
        migrations.CreateModel(
            name='RoleD',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=150)),
                ('discription', models.TextField(blank=True, null=True)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('id_group', models.ForeignKey(db_column='id_group', on_delete=django.db.models.deletion.CASCADE, to='main.groupd')),
            ],
            options={
                'db_table': 'Role_d',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('prizvische', models.CharField(db_column='Prizvische', max_length=100)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('father_name', models.CharField(db_column='Father_Name', max_length=100)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('auth_user', models.OneToOneField(blank=True, db_column='auth_user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('id_dep', models.ForeignKey(db_column='id_dep', default=1, on_delete=django.db.models.deletion.PROTECT, to='main.department')),
                ('id_pos', models.ForeignKey(db_column='id_pos', on_delete=django.db.models.deletion.PROTECT, to='main.dictpos')),
            ],
            options={
                'db_table': 'User_list',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, to='main.roled')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='userrole_set', to='main.userlist')),
            ],
            options={
                'db_table': 'User_role',
                'unique_together': {('id_role', 'id_user')},
            },
        ),
    ]
