# Generated by Django 5.2.8 on 2026-06-06 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='id_pos',
            field=models.ForeignKey(blank=True, db_column='id_pos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.dictpos'),
        ),
    ]
